use std::env;

use jiff::{
    SpanRound, Timestamp, ToSpan, Unit,
    civil::date,
    fmt::friendly::{Designator, SpanPrinter},
    tz::TimeZone,
};

fn main() {
    let args: Vec<String> = env::args().collect();
    let tz_name = args.get(1).map(String::as_str).unwrap_or("America/Chicago");

    let tz = TimeZone::get(tz_name).unwrap();
    let now = Timestamp::now().to_zoned(tz.clone());

    // Truncate to year starts and ends +/- 5 years worth
    let from = date(now.year() - 5, 1, 1)
        .at(0, 0, 0, 0)
        .to_zoned(tz.clone())
        .unwrap()
        .timestamp();
    let to = date(now.year() + 6, 1, 1)
        .at(0, 0, 0, 0)
        .to_zoned(tz.clone())
        .unwrap()
        .timestamp();

    let tz_name_short = tz_name.split("/").last().unwrap();

    // X-WR- for compatibility with Apple client
    let mut out = format!(
        "BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//daylightsaved.ntay//{title}//EN
NAME:{title}
X-WR-CALNAME:{title}
DESCRIPTION:{desc}
X-WR-CALDESC:{desc}
TIMEZONE-ID:{tz_name}
X-WR-TIMEZONE:{tz_name}
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:{tz_name}
END:VTIMEZONE\n\n",
        title = format!("{} DST Transitions", tz_name_short),
        // TODO: 'URL:'
        desc = format!(
            "Daylight Savings Transitions data for {}. [Automagically generated by DaylightSaved]",
            tz_name
        ),
    );

    let events_ics: Vec<String> =
        tz
            .following(from)
            .take_while(|t| t.timestamp() <= to)
            .collect::<Vec<_>>()
            .array_windows::<2>()
            .map(|[t1, t2]| {
                let z = t2.timestamp().to_zoned(tz.clone());

                // Move time is a bit complicated in TZif transitions, as it's
                // actually implicit. The transition defines the new time that takes
                // effect on a given date. The resulting timezone then implies when
                // the clock must have changed for that to happen.
                //
                // e.g. UTC-6 -> UTC-5 03:00. 1hr difference in TZ. So the change
                //      must have occurred at 02:00 (where this 02:00 never actually
                //      happened, because the clock jumped!)
                let offset_diff_secs = t2.offset().seconds() - t1.offset().seconds();
                // Because this time never happened, we must down-convert to a 'civil' datetime
                // to better represent this.
                let move_dt = z.datetime() - offset_diff_secs.seconds();
                // Let's display this nicely for the user (with jiff's printer settings)
                let printer = SpanPrinter::new()
                    .spacing(jiff::fmt::friendly::Spacing::BetweenUnitsAndDesignators)
                    .designator(Designator::Verbose);
                let move_duration_text = printer.span_to_string(
                    &offset_diff_secs.abs().seconds().round(SpanRound::new().largest(Unit::Hour)).unwrap());

                let summary = format!(
                    "TZ: {tz_short} DST {starts_or_ends} ({plus_minus}{move_duration_text}, to UTC{new_offset})",
                    tz_short = tz_name_short,
                    starts_or_ends = if t2.dst().is_dst() { "Starts" } else { "Ends" },
                    plus_minus = if offset_diff_secs > 0 { "+" } else { "-" },
                    new_offset = t2.offset(),
                );

                let desc = format!(
                    "{tz_name} transition from UTC{old_offset} to UTC{new_offset}.
Going from {old_dst_or_st} ({old_abbrev}) Time into {new_dst_or_st} ({new_abbrev}) Time.
Clock moves {move_duration_text} {forward_backward} at {move_time} ({old_abbrev}) to {new_time} ({new_abbrev}).

[powered with DaylightSaved by github.com/nicholastay]",
                    old_offset = t1.offset(),
                    new_offset = t2.offset(),
                    old_abbrev = t1.abbreviation(),
                    new_abbrev = t2.abbreviation(),
                    old_dst_or_st = if t1.dst().is_std() { "Standard" } else { "Daylight Savings" },
                    new_dst_or_st = if t2.dst().is_dst() { "Daylight Savings" } else { "Standard" },
                    forward_backward = if offset_diff_secs > 0 { "FORWARD" } else { "BACKWARD" },
                    move_time = move_dt.strftime("%H:%M"),
                    new_time = z.strftime("%H:%M"),
                ).replace("\n", "\\n");  // ics spec needs escaped '\n' literally

                format!(
                    "BEGIN:VEVENT
UID:{tz_name_short}-dst-{ymd}@daylightsaved.ntay
DTSTART;value=date:{ymd}
DTEND;value=date:{ymd1}
SUMMARY:{summary}
DESCRIPTION:{desc}
END:VEVENT",
                    ymd = z.strftime("%Y%m%d"),
                    // all-day events must 'end' on the following day, suppsedly also for outlook support
                    ymd1 = (z + 1.day()).strftime("%Y%m%d"),
                )
            })
            .collect();

    out.push_str(String::as_str(&events_ics.join("\n\n")));
    out.push_str("\n\nEND:VCALENDAR");

    println!("{}", out);
}
